name: Prebuild

on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version:
        - 8.x
        - 10.x
        - 12.x
        - 14.x
        - 16.x
        os:
        # - macos-latest
        - ubuntu-latest
        - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      env:
        PYTHON_VERSION: 3.8
    - name: Install MSBuild
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.2
    - run: npm i
    - name: Build binaries
      run: npx prebuild --strip
    - name: Test
      run: npm test
    - name: Upload prebuilds
      if: startsWith(github.ref, 'refs/tags/v')
      run: npx prebuild --strip -u ${{ secrets.GITHUB_TOKEN }}
